// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uitmzfxpkpyccmharejn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpdG16Znhwa3B5Y2NtaGFyZWpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDc3NDMsImV4cCI6MjA2NjM4Mzc0M30.mqD9b3_Bnisf1NRgKb7cFOAOtDpKWnQDSMkFcUXNWuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);